[package]
name = "msa-to-st-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
egui = "0.15"
eframe = "0.15"
rayon = "1.5"
rfd = "0.10"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"